name: Generate Calendars and Update Sitemap

on:
  schedule:
    # Run monthly on the 1st at 00:00 UTC
    - cron: '0 0 1 * *'
  workflow_dispatch:  # Allows manual trigger
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'tsconfig.json'
      - '.github/workflows/generate-and-update.yml'

jobs:
  generate-and-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install Node.js dependencies
      run: npm ci
    
    - name: Generate calendar files
      run: npm run generate
    
    - name: Generate sitemap
      run: npm run sitemap
        
    - name: Check for changes
      id: check_changes
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected:"
          git status --short
        else
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        fi
        
    - name: Commit and push if changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        git commit -m "Update holiday calendars and sitemap [automated]"
        git push
    
    - name: No changes detected
      if: steps.check_changes.outputs.changes == 'false'
      run: |
        echo "No changes to calendars or sitemap - skipping commit"
