name: Generate Calendars and Update Sitemap

on:
  schedule:
    # Run monthly on the 1st at 00:00 UTC
    - cron: '0 0 1 * *'
  workflow_dispatch:  # Allows manual trigger
  push:
    branches: [ main ]
    paths:
      - 'holidays/scripts/generate_holidays_at.py'
      - 'holidays/scripts/generate_holidays_de.py'
      - 'holidays/scripts/generate_school_holidays.py'
      - 'generate_sitemap.py'
      - '.github/workflows/generate-and-update.yml'

jobs:
  generate-and-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      run: |
        if [ -f holidays/scripts/requirements.txt ]; then
          pip install -r holidays/scripts/requirements.txt
        fi
    
    - name: Generate calendar files
      run: |
        cd holidays
        python scripts/generate_holidays_at.py
        python scripts/generate_school_holidays.py
        python scripts/generate_holidays_de.py
        cd ..
    
    - name: Generate main sitemap
      run: |
        python generate_sitemap.py
        
    - name: Check for changes
      id: check_changes
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected:"
          git status --short
        else
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        fi
        
    - name: Commit and push if changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        git commit -m "Update holiday calendars and sitemap [automated]"
        git push
    
    - name: No changes detected
      if: steps.check_changes.outputs.changes == 'false'
      run: |
        echo "No changes to calendars or sitemap - skipping commit"
